name: Build and Release Wosb AppImage

on:
  push:
    tags:
      - 'v*'  # Запускается при создании тега, например, v1.0.0
  workflow_dispatch: # Возможность вручную запустить workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        # Загрузка и установка 7-Zip через curl
        curl -L -o 7z2408-linux-x64.tar.xz https://www.7-zip.org/a/7z2408-linux-x64.tar.xz
        tar -xf 7z2408-linux-x64.tar.xz
        sudo mv 7zz /usr/local/bin/7z
        # Установка других зависимостей
        sudo apt-get update
        sudo apt-get install -y desktop-file-utils xvfb

    - name: Run fetch.sh
      run: |
        chmod +x ./fetch.sh
        ./fetch.sh

    - name: Prepare AppDir structure
      run: |
        mkdir -p Wosb.AppDir/usr/bin
        mkdir -p Wosb.AppDir/app/wine

    - name: Run build.sh
      run: |
        chmod +x ./build.sh
        xvfb-run ./build.sh

    - name: Upload Wosb AppImage to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: Wosb-x86_64.AppImage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}